"""baseline

Revision ID: a1c5c8bbad37
Revises: 
Create Date: 2026-04-20 20:10:13.674084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1c5c8bbad37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_discovery_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seed_node', sa.Text(), nullable=False),
    sa.Column('max_hops', sa.Integer(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_by', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_discovery_runs_seed_node'), 'auto_discovery_runs', ['seed_node'], unique=False)
    op.create_index(op.f('ix_auto_discovery_runs_started_at'), 'auto_discovery_runs', ['started_at'], unique=False)
    op.create_table('bgp_neighbors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_name', sa.Text(), nullable=False),
    sa.Column('neighbor_ip', sa.Text(), nullable=False),
    sa.Column('remote_asn', sa.Integer(), nullable=False),
    sa.Column('local_asn', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('prefixes_received', sa.Integer(), nullable=True),
    sa.Column('prefixes_sent', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('vrf', sa.Text(), nullable=False),
    sa.Column('address_family', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name', 'neighbor_ip', 'vrf', 'address_family', name='uq_bgp_node_neighbor_vrf_af')
    )
    op.create_index(op.f('ix_bgp_neighbors_collected_at'), 'bgp_neighbors', ['collected_at'], unique=False)
    op.create_index(op.f('ix_bgp_neighbors_node_name'), 'bgp_neighbors', ['node_name'], unique=False)
    op.create_table('change_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_source', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_history_changed_at'), 'change_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_change_history_target_id'), 'change_history', ['target_id'], unique=False)
    op.create_index(op.f('ix_change_history_target_type'), 'change_history', ['target_type'], unique=False)
    op.create_table('collection_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('devices_queried', sa.Integer(), nullable=True),
    sa.Column('endpoints_found', sa.Integer(), nullable=True),
    sa.Column('endpoints_new', sa.Integer(), nullable=True),
    sa.Column('endpoints_updated', sa.Integer(), nullable=True),
    sa.Column('endpoints_moved', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_started_at'), 'collection_runs', ['started_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_target_id'), 'comments', ['target_id'], unique=False)
    op.create_index(op.f('ix_comments_target_type'), 'comments', ['target_type'], unique=False)
    op.create_table('device_polls',
    sa.Column('device_name', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_duration', sa.Float(), nullable=True),
    sa.Column('next_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_sec', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('device_name', 'job_type', name='pk_device_polls')
    )
    op.create_table('discovery_excludes',
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('endpoint_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_events_event_type'), 'endpoint_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_endpoint_events_mac_address'), 'endpoint_events', ['mac_address'], unique=False)
    op.create_index(op.f('ix_endpoint_events_timestamp'), 'endpoint_events', ['timestamp'], unique=False)
    op.create_table('endpoint_probes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mac', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('probe_type', sa.Text(), nullable=False),
    sa.Column('tcp_port', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('probed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_probes_mac'), 'endpoint_probes', ['mac'], unique=False)
    op.create_index(op.f('ix_endpoint_probes_probed_at'), 'endpoint_probes', ['probed_at'], unique=False)
    op.create_table('endpoint_watches',
    sa.Column('mac_address', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('mac_address')
    )
    op.create_table('endpoints',
    sa.Column('mac_address', sa.Text(), nullable=False),
    sa.Column('current_switch', sa.Text(), nullable=False),
    sa.Column('current_port', sa.Text(), nullable=False),
    sa.Column('current_vlan', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_uplink', sa.Boolean(), nullable=False),
    sa.Column('current_ip', sa.Text(), nullable=True),
    sa.Column('additional_ips', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mac_vendor', sa.Text(), nullable=True),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('classification_confidence', sa.Text(), nullable=True),
    sa.Column('classification_override', sa.Boolean(), nullable=False),
    sa.Column('dhcp_server', sa.Text(), nullable=True),
    sa.Column('dhcp_lease_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dhcp_lease_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('mac_address', 'current_switch', 'current_port', 'current_vlan', name='pk_endpoints_mac_loc')
    )
    op.create_index(op.f('ix_endpoints_active'), 'endpoints', ['active'], unique=False)
    op.create_table('ip_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=False),
    sa.Column('mac_address', sa.Text(), nullable=True),
    sa.Column('ports_open', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('banners', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snmp_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('http_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tls_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ssh_banner', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('dns_name', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_observations_ip_address'), 'ip_observations', ['ip_address'], unique=False)
    op.create_index(op.f('ix_ip_observations_mac_address'), 'ip_observations', ['mac_address'], unique=False)
    op.create_index(op.f('ix_ip_observations_observed_at'), 'ip_observations', ['observed_at'], unique=False)
    op.create_table('kv_config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('node_arp_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_name', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('mac', sa.Text(), nullable=False),
    sa.Column('interface', sa.Text(), nullable=False),
    sa.Column('vrf', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name', 'ip', 'mac', 'vrf', name='uq_arp_node_ip_mac_vrf')
    )
    op.create_index(op.f('ix_node_arp_entries_collected_at'), 'node_arp_entries', ['collected_at'], unique=False)
    op.create_index(op.f('ix_node_arp_entries_node_name'), 'node_arp_entries', ['node_name'], unique=False)
    op.create_table('node_fib_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_name', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('next_hop', sa.Text(), nullable=False),
    sa.Column('interface', sa.Text(), nullable=True),
    sa.Column('vrf', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name', 'prefix', 'next_hop', 'vrf', name='uq_fib_node_prefix_nh_vrf')
    )
    op.create_index(op.f('ix_node_fib_entries_collected_at'), 'node_fib_entries', ['collected_at'], unique=False)
    op.create_index(op.f('ix_node_fib_entries_node_name'), 'node_fib_entries', ['node_name'], unique=False)
    op.create_table('node_lldp_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_name', sa.Text(), nullable=False),
    sa.Column('local_interface', sa.Text(), nullable=False),
    sa.Column('remote_system_name', sa.Text(), nullable=False),
    sa.Column('remote_port', sa.Text(), nullable=False),
    sa.Column('remote_chassis_id', sa.Text(), nullable=True),
    sa.Column('remote_management_ip', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name', 'local_interface', 'remote_system_name', 'remote_port', name='uq_lldp_node_iface_remote')
    )
    op.create_index(op.f('ix_node_lldp_entries_collected_at'), 'node_lldp_entries', ['collected_at'], unique=False)
    op.create_index(op.f('ix_node_lldp_entries_node_name'), 'node_lldp_entries', ['node_name'], unique=False)
    op.create_table('node_mac_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_name', sa.Text(), nullable=False),
    sa.Column('mac', sa.Text(), nullable=False),
    sa.Column('interface', sa.Text(), nullable=False),
    sa.Column('vlan', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name', 'mac', 'interface', 'vlan', name='uq_mac_node_mac_iface_vlan')
    )
    op.create_index(op.f('ix_node_mac_entries_collected_at'), 'node_mac_entries', ['collected_at'], unique=False)
    op.create_index(op.f('ix_node_mac_entries_node_name'), 'node_mac_entries', ['node_name'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_name', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('next_hop', sa.Text(), nullable=False),
    sa.Column('protocol', sa.Text(), nullable=False),
    sa.Column('vrf', sa.Text(), nullable=False),
    sa.Column('metric', sa.Integer(), nullable=True),
    sa.Column('preference', sa.Integer(), nullable=True),
    sa.Column('outgoing_interface', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name', 'prefix', 'next_hop', 'vrf', name='uq_routes_node_prefix_nh_vrf')
    )
    op.create_index(op.f('ix_routes_collected_at'), 'routes', ['collected_at'], unique=False)
    op.create_index(op.f('ix_routes_node_name'), 'routes', ['node_name'], unique=False)
    op.create_index(op.f('ix_routes_prefix'), 'routes', ['prefix'], unique=False)
    op.create_table('sweep_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cidr', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=True),
    sa.Column('total_alive', sa.Integer(), nullable=True),
    sa.Column('total_onboarded', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sweep_runs_started_at'), 'sweep_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sweep_runs_started_at'), table_name='sweep_runs')
    op.drop_table('sweep_runs')
    op.drop_index(op.f('ix_routes_prefix'), table_name='routes')
    op.drop_index(op.f('ix_routes_node_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_collected_at'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_node_mac_entries_node_name'), table_name='node_mac_entries')
    op.drop_index(op.f('ix_node_mac_entries_collected_at'), table_name='node_mac_entries')
    op.drop_table('node_mac_entries')
    op.drop_index(op.f('ix_node_lldp_entries_node_name'), table_name='node_lldp_entries')
    op.drop_index(op.f('ix_node_lldp_entries_collected_at'), table_name='node_lldp_entries')
    op.drop_table('node_lldp_entries')
    op.drop_index(op.f('ix_node_fib_entries_node_name'), table_name='node_fib_entries')
    op.drop_index(op.f('ix_node_fib_entries_collected_at'), table_name='node_fib_entries')
    op.drop_table('node_fib_entries')
    op.drop_index(op.f('ix_node_arp_entries_node_name'), table_name='node_arp_entries')
    op.drop_index(op.f('ix_node_arp_entries_collected_at'), table_name='node_arp_entries')
    op.drop_table('node_arp_entries')
    op.drop_table('kv_config')
    op.drop_index(op.f('ix_ip_observations_observed_at'), table_name='ip_observations')
    op.drop_index(op.f('ix_ip_observations_mac_address'), table_name='ip_observations')
    op.drop_index(op.f('ix_ip_observations_ip_address'), table_name='ip_observations')
    op.drop_table('ip_observations')
    op.drop_index(op.f('ix_endpoints_active'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_table('endpoint_watches')
    op.drop_index(op.f('ix_endpoint_probes_probed_at'), table_name='endpoint_probes')
    op.drop_index(op.f('ix_endpoint_probes_mac'), table_name='endpoint_probes')
    op.drop_table('endpoint_probes')
    op.drop_index(op.f('ix_endpoint_events_timestamp'), table_name='endpoint_events')
    op.drop_index(op.f('ix_endpoint_events_mac_address'), table_name='endpoint_events')
    op.drop_index(op.f('ix_endpoint_events_event_type'), table_name='endpoint_events')
    op.drop_table('endpoint_events')
    op.drop_table('discovery_excludes')
    op.drop_table('device_polls')
    op.drop_index(op.f('ix_comments_target_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_target_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_collection_runs_started_at'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_change_history_target_type'), table_name='change_history')
    op.drop_index(op.f('ix_change_history_target_id'), table_name='change_history')
    op.drop_index(op.f('ix_change_history_changed_at'), table_name='change_history')
    op.drop_table('change_history')
    op.drop_index(op.f('ix_bgp_neighbors_node_name'), table_name='bgp_neighbors')
    op.drop_index(op.f('ix_bgp_neighbors_collected_at'), table_name='bgp_neighbors')
    op.drop_table('bgp_neighbors')
    op.drop_index(op.f('ix_auto_discovery_runs_started_at'), table_name='auto_discovery_runs')
    op.drop_index(op.f('ix_auto_discovery_runs_seed_node'), table_name='auto_discovery_runs')
    op.drop_table('auto_discovery_runs')
    # ### end Alembic commands ###
